---
layout: post
title: "Python で import するときに locale 関係でエラー"
date: 2016-09-26 08:59
---

## エラー内容

あるライブラリを import した時に以下のようなエラーが出てしまった

{% highlight shell %}
raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8
{% endhighlight %}

## 解決方法

以下のリンクを参考に修正した

[Pelican 3.3 pelican-quickstart error “ValueError: unknown locale: UTF-8](http://stackoverflow.com/questions/19961239/pelican-3-3-pelican-quickstart-error-valueerror-unknown-locale-utf-8)

どうやら [Python のバグ](https://bugs.python.org/issue18378)で、言語設定が英語だと getDefaultLocale なるメソッドがこけるらしい

具体的な Workaround として以下のロケール付きのUTF8として環境変数をセットすることで回避できた

{% highlight shell %}
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
{% endhighlight %}
